# Generated by Django 3.1.3 on 2020-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('errorid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('errorseverity', models.CharField(max_length=8)),
                ('errorcategory', models.CharField(max_length=10)),
                ('errormessage', models.CharField(max_length=38)),
                ('longmessage', models.CharField(max_length=56)),
                ('errortime', models.IntegerField()),
                ('selected', models.CharField(max_length=5)),
                ('new', models.CharField(max_length=5)),
                ('expanded', models.CharField(max_length=5)),
            ],
        ),
    ]
