export const SET_ALERTS = "SET_ALERTS";
export const START_ADDING_ALERTS = "START_ADDING_ALERTS";
export const SET_SATELLITES = "SET_SATELLITES";
export const START_ADDING_SATELLITES = "START_ADDING_SATELLITES";
export const CREATE_USER = "CREATE_USER";
export const LOGOUT = "LOGOUT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
