# Generated by Django 3.1.3 on 2020-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('contactid', models.CharField(max_length=36)),
                ('contactstatus', models.CharField(max_length=8)),
                ('contactname', models.IntegerField()),
                ('contactground', models.CharField(max_length=8)),
                ('contactsatellite', models.CharField(max_length=7)),
                ('contactequipment', models.CharField(max_length=42)),
                ('contactstate', models.CharField(max_length=9)),
                ('contactstep', models.CharField(max_length=19)),
                ('contactdetail', models.CharField(max_length=123)),
                ('contactbegintimestamp', models.IntegerField()),
                ('contactendtimestamp', models.IntegerField()),
                ('contactlatitude', models.IntegerField()),
                ('contactlongitude', models.IntegerField()),
                ('contactazimuth', models.IntegerField()),
                ('contactelevation', models.IntegerField()),
                ('contactresolution', models.CharField(max_length=9)),
                ('contactresolutionstatus', models.CharField(max_length=8)),
            ],
        ),
    ]
