# Generated by Django 3.1.3 on 2020-11-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('error_id', models.UUIDField()),
                ('error_severity', models.CharField(max_length=191)),
                ('error_category', models.CharField(max_length=191)),
                ('error_message', models.CharField(max_length=191)),
                ('long_message', models.TextField()),
                ('error_time', models.IntegerField()),
                ('selected', models.BooleanField()),
                ('new', models.BooleanField()),
                ('expanded', models.BooleanField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_id', models.CharField(max_length=191)),
                ('contact_id', models.UUIDField()),
                ('contact_status', models.CharField(max_length=191)),
                ('contact_name', models.IntegerField()),
                ('contact_ground', models.CharField(max_length=191)),
                ('contact_satellite', models.CharField(max_length=191)),
                ('contact_equipment', models.CharField(max_length=191)),
                ('contact_state', models.CharField(max_length=191)),
                ('contact_step', models.CharField(max_length=191)),
                ('contact_detail', models.TextField()),
                ('contact_begin_timestamp', models.IntegerField()),
                ('contact_end_timestamp', models.IntegerField()),
                ('contact_latitude', models.FloatField()),
                ('contact_longitude', models.FloatField()),
                ('contact_azimuth', models.FloatField()),
                ('contact_elevation', models.FloatField()),
                ('contact_resolution', models.CharField(max_length=191)),
                ('contact_resolution_status', models.CharField(max_length=191)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
