"""Initial migration

Revision ID: 54bc3855e9e4
Revises: 
Create Date: 2021-04-03 11:19:59.685325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bc3855e9e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('errorId', sa.String(length=200), nullable=True),
    sa.Column('errorSeverity', sa.String(length=200), nullable=True),
    sa.Column('errorCategory', sa.String(length=200), nullable=True),
    sa.Column('errorMessage', sa.String(length=200), nullable=True),
    sa.Column('longMessage', sa.Text(), nullable=True),
    sa.Column('errorTime', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('new', sa.Boolean(), nullable=True),
    sa.Column('expanded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('errorId')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_id', sa.String(length=200), nullable=True),
    sa.Column('contactId', sa.String(length=200), nullable=True),
    sa.Column('contactStatus', sa.String(length=200), nullable=True),
    sa.Column('contactName', sa.Integer(), nullable=True),
    sa.Column('contactGround', sa.String(length=200), nullable=True),
    sa.Column('contactSatellite', sa.String(length=200), nullable=True),
    sa.Column('contactEquipment', sa.String(length=200), nullable=True),
    sa.Column('contactState', sa.String(length=200), nullable=True),
    sa.Column('contactStep', sa.String(length=200), nullable=True),
    sa.Column('contactDetail', sa.Text(), nullable=True),
    sa.Column('contactBeginTimestamp', sa.Integer(), nullable=True),
    sa.Column('contactEndTimestamp', sa.Integer(), nullable=True),
    sa.Column('contactLatitude', sa.Integer(), nullable=True),
    sa.Column('contactLongitude', sa.Integer(), nullable=True),
    sa.Column('contactAzimuth', sa.Integer(), nullable=True),
    sa.Column('contactElevation', sa.Integer(), nullable=True),
    sa.Column('contactResolution', sa.String(length=200), nullable=True),
    sa.Column('contactResolutionStatus', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    op.drop_table('alert')
    # ### end Alembic commands ###
